### ISSUE TITLE
Crash on startup while using profiles in kodi

### ISSUE THREAD

**Issue by hawkeyexp** [rmrector/script.artwork.beef#12]
Today i changed to use two profiles in kodi. Artwork Beef (service) has a startup bug cause it tries to get properties via json which will fail until a profile is loeaded. A condition should be added to check if a profile is loaded etc.

**Comment by rmrector** [comment]
Thanks for the report. I can recreate this in Kodi 18 Leia, is that the version of Kodi you are using?

Artwork Beef is configured to start after profile login, but Leia is starting it on application start as well. I'm working on a PR to Kodi that will resolve this for all add-ons.

**Comment by rmrector** [comment]
And [here is the PR to Kodi](https://github.com/xbmc/xbmc/pull/13796).

Crashing the service is an extreme reaction from Artwork Beef; other add-ons likely react in a different way or just don't access JSON-RPC until later anyway. While Artwork Beef is in beta I like these errors big and loud so I have a better chance to see them.

**Comment by rmrector** [comment]
That PR was accepted, so this shouldn't happen with new Kodi 18 Leia nightlies.
