### ISSUE TITLE
Exception Thrown with v 0.20.0 running K*18 nightly on Win x64

### ISSUE THREAD

**Issue by mgonzales71** [rmrector/script.artwork.beef#15]
Just noticed an artwork beef error popup while watching movie....
wanted to post this since I don't see any open issues and never seen this error since updating just a little big ago.

I can give you a better (full debug) log after the movie but had a quick min to post this now...

```

08:11:44.434 T:17192  NOTICE: VideoInfoScanner: Starting scan ..
08:11:49.316 T:17192   ERROR: XFILE::CDirectory::GetDirectory - Error getting
08:13:32.924 T:17192   ERROR: Previous line repeats 1 times.
08:13:32.924 T:17192  NOTICE: CVideoDatabase::CleanDatabase: Starting videodatabase cleanup ..
08:13:39.468 T:17192  NOTICE: CVideoDatabase::CleanDatabase: Cleaning videodatabase done. Operation took 00:06
08:13:39.473 T:17192  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 01:55
08:17:11.875 T:11172   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'services_hit' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.artwork.beef\service.py", line 363, in <module>
                                                ArtworkService().run()
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.artwork.beef\service.py", line 103, in run
                                                if self.process_allvideos(self.processed.is_stale):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.artwork.beef\service.py", line 233, in process_allvideos
                                                return self.processor.process_medialist(items)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 205, in process_medialist
                                                return self.process_chunkedlist([medialist], 1, alwaysnotify)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 218, in process_chunkedlist
                                                self._process_chunk(medialist, idx + 1, alwaysnotify)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 243, in _process_chunk
                                                services_hit = self._process_item(mediaitem, singleitem)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 298, in _process_item
                                                sh, er = self.downloader.downloadfor(mediaitem)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\filemanager.py", line 114, in downloadfor
                                                return services_hit, error
                                            UnboundLocalError: local variable 'services_hit' referenced before assignment
                                            -->End of Python script error report<--

```

Thanks!

Mario

**Comment by mgonzales71** [comment]
Ok,

Had some time to look at this.  First decided to grab v0.20.1~adev but looking closer there don't seem to be any changes yet.

So decided to go ahead and delete the the DB, report and recreate the settings and see if that had any impact...

It appears that it did...

I am not sure what really what particular setting(s) resolved this but here are the 2 settings xml files if you wanted to peek at them.  API key redacted otherwise they are both the same that, I used when I got the exception (more then once running "for all video old and new" scan.

**orig settings that threw exception:**

[settings-exception.xml.txt](https://github.com/rmrector/script.artwork.beef/files/2055296/settings-exception.xml.txt)

**newly created from scratch settings (differs a little from previous) that no longer throws an exception:**

[settings-no-exception.xml.txt](https://github.com/rmrector/script.artwork.beef/files/2055297/settings-no-exception.xml.txt)

Thanks Ryan!

Mario

**Comment by mgonzales71** [comment]
Side Q:  

Does Episode thumbs get downloaded by default or do I need to use the setting to do that?

    <setting id="episode.download_arttypes">thumb</setting>

**Comment by rmrector** [comment]
Thanks for the report, I see what is going wrong. I'll have a fix in the next update.

Side A: Yes, 'thumb' will need to be added to those two settings to download and identify local thumbs.

**Comment by rmrector** [comment]
Version 0.20.1 should resolve this error.

**Comment by mgonzales71** [comment]
just updated yesterday and ran a full old/new video update without (1st) and then with "Thumb" for Episodes and no errors either way.

Curious - does adding "thumb" actually do anything yet?

But hey many thanks for all your help and especially this and your other addons.  Love the webdev addon.   Saves my sanity when working on Kodi skins.

want a challenge?  a Kodi Skin IDE / Editor :-)   a few have started over the years hehe.  

Thanks and take care!

Mario

**Comment by rmrector** [comment]
"thumb" must be in the "Additional art types for TV episodes" for Artwork Beef to add "thumb" images from the local file system, and it must be in "Download these artwork types" for Artwork Beef to download external URLs from scrapers or JSON-RPC.  Artwork Beef doesn't currently add new "thumb" images from web services; the thumbnails available from TheTVDB are universally awful and I haven't quite decided how to configure picking episode 'fanart' and episode 'thumb' from TheMovieDB.
