### ISSUE TITLE
posters with title problem

### ISSUE THREAD

**Issue by tcamargo** [rmrector/script.artwork.beef#16]
Hi,

I just setup Artwork Beef and it is working great except that every poster is being downloaded without title. The "Prefer poster with no title" option is off. Would you please let me know what you need to further debug this? 

Thanks!

**Comment by tcamargo** [comment]
Hi!

* Kodi 17.6
* Artwork Beef 0.20.3
* Estuary skin
* No NFOs. Removed them before starting a new clean library
* Artwork Beef is downloading media files. Keyart is disable.
![image](https://user-images.githubusercontent.com/52097/42252867-3a1cc18c-7f15-11e8-9d2f-52e295771cc7.png)
* If I remove the downloaded poster and refresh the movie in Kodi, it shows the poster with title. 
* Kodi debug log: https://pastebin.com/e6Sc8pi0
* artwork-report: https://pastebin.com/Z6FykhQE

Thx!

**Comment by rmrector** [comment]
Do the movies not yet processed by Artwork Beef already have posters from the scraper? Do those posters have a title? If a poster image exists but they do not have a title then something in the scraper needs configured, Artwork Beef is just downloading the image that the scraper adds.

If you open the context menu on one of those movies and select "Manage ..." then "AB: Add missing artwork", is the poster image that Artwork Beef downloads different than the original poster from the scraper?

**Comment by tcamargo** [comment]
If I set keyart to 1 and leave "Prefer poster with no title" off, Artwork Beef finally downloaded the poster  with a title.
![image](https://user-images.githubusercontent.com/52097/42296963-b1ecbd22-7fd1-11e8-931c-6d5121ae23f4.png)

**Comment by rmrector** [comment]
That's the ticket, thanks!

I can recreate this now, so a fix is inevitable.

**Comment by rmrector** [comment]
Fixed in 0.21.0, thanks for the report.
