### ISSUE TITLE
Skip for selected folder

### ISSUE THREAD

**Issue by hablaras** [rmrector/script.artwork.beef#18]
Hi,

Would it be possible to add an option to skip Artwork Beef for certain folders that have been scanned to the Kodi library? E.g. via a wildcard like "%\homemovies\2018"

I have one huge home movies folder with 2500+ movies. If I scan "old and new" movies, it will always try to lookup artwork for those movies as well, which is nonsense.

Thanks for the great addon anyways!

**Comment by rmrector** [comment]
Probably a good idea.

As long as these movies don't have a web service ID (like an IMDB number) from an NFO it's not looking up artwork online, though, just a quicker file system check.

**Comment by hablaras** [comment]
They don't have a web service id like a TMDB or IMDB number.

Still, on my RPi3 it takes quite some time to process every "old, new and between" movie every day.

Perhaps an even simpler checkbox: "skip every check if web service ID is missing"?

**Comment by rmrector** [comment]
DO NOT RUN "old, new, and inbetween" EVERY DAY! The whole point of the automatic processing is to handle checking for updates at a SENSIBLE pace.

I guarantee you most days there will be no new artwork for any of the old items, and you are just wasting time and a massive amount of web service resources doing so.

**Comment by rmrector** [comment]
Implemented with #47.

**Comment by hablaras** [comment]
Wow, installed the 0.27.2~adev version and tested it. It now skips my huge homemovie folder.

Thanks rmrector and supmagc, it's the best addon for Kodi.

**Comment by rmrector** [comment]
This feature officially in version 0.28.0.
