### ISSUE TITLE
Artwork Beef Crashes on first run

### ISSUE THREAD

**Issue by dawsonjw** [rmrector/script.artwork.beef#19]
Hi,
   firstly thanks for writing this add-on.  I have used it before but I had to re-install everything after a corruption.  Anyway after installing artwork beef I am having problem scanning the music database, videos works fine.

I seems to crash on the first album.  Could it possibly be the album name as it actually ends with a ! character?

I have uploaded a log hoping this will help

http://paste.kodi.tv/tepukohopi

cheers

John

**Comment by rmrector** [comment]
This is caused by a recent change in Kodi. The fix is being worked on in [PR #14201](https://github.com/xbmc/xbmc/pull/14201) to Kodi core.

**Comment by dawsonjw** [comment]
Thanks Ryan. You have a nice day

Cheers 

John

**Comment by rmrector** [comment]
This PR was merged a couple days ago, fresh nightlies should be fixed.

**Comment by dawsonjw** [comment]
Hi Ryan 
      Thanks for that.  Downloaded it today and it works just fine

Really appreciate your help

Cheers 

John
