### ISSUE TITLE
Add option to retrieve TV show artwork from TheMovieDB

### ISSUE THREAD

**Issue by rmrector** [rmrector/script.artwork.beef#22]

**Comment by monisriz** [comment]
I feel this would be a great addition to an already fantastic addon whenever it happens. Tvdb and Fanart.tv cover a lot of bases, TMDB is much better for highres artwork. The difference in image quality becomes even more apparent when using a projector or a big screen 4k tv.

I think the only TMDB-based artwork supported by AB currently is season posters and episode fanart. Adding TMDB support for Episode thumbnails would be amazing as thumbs at TVDB are lowres (400x225) and look bad when using a projector or big 4k screen. Same applies for posters (680x1000).
