### ISSUE TITLE
AudioDb.com Error

### ISSUE THREAD

**Issue by dawsonjw** [rmrector/script.artwork.beef#30]
Hi Ryan,
      just put up a few new albums and noticed the artwork beef is reporting and error accessing audiodb.com   Is that a problem at your end of some other mysterious ailment in another place

cheers

John

**Comment by rmrector** [comment]
What device, OS, and version of Kodi are you using?

**Comment by dawsonjw** [comment]
Hi Ryan,
    I am using a Minix Neo U1, running Android.  The Kodi version is latest Beta 180825

cheers

john

**Comment by rmrector** [comment]
Thanks. I reported this to TADB and zag fixed it right up. A quick test on my end works now, give it a try.

**Comment by dawsonjw** [comment]
Hi Ryan,
            thanks for that.  Yup works fine now.  Sorry to bug you when it turned out to be a problem elsewhere.  Doh

cheers

John

**Comment by rmrector** [comment]
No worries, it wasn't exactly a problem with TADB but a combination of their server setup and certain client setups.
