### ISSUE TITLE
fanart.tv Invalid project API key

### ISSUE THREAD

**Issue by schumi2004** [rmrector/script.artwork.beef#31]
Today i noticed i was missing some fanart so i started to retrieve them manually using artwork.beef but it constantly gave me Invalid project API key messages.
So i started to add my own fanart.tv key but that didn;t worked either.
Did i do something wrong or has fanart.tv changed his terms of use?

19:24:53.806 T:20308   ERROR: CCurlFile::Stat - Failed: Peer certificate cannot be authenticated with given CA certificates(60) for https://assets.fanart.tv/fanart/tv/317953/hdtvlogo/iron-fist-2017-589781e36a330.png
19:24:57.583 T:19164   ERROR: Previous line repeats 1 times.
19:24:57.583 T:19164   ERROR: CCurlFile::Stat - Failed: Peer certificate cannot be authenticated with given CA certificates(60) for https://assets.fanart.tv/fanart/tv/317953/tvbanner/iron-fist-2017-589f206e1b0f8.jpg
19:24:58.820 T:19164   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 500
19:24:58.820 T:19164   ERROR: CCurlFile::Open failed with code 500 for https://assets.fanart.tv/fanart/tv/317953/tvbanner/iron-fist-2017-589f206e1b0f8.jpg:
19:25:02.439 T:20920 WARNING: [script.artwork.beef] Error with provider 'fanart.tv': Invalid project API key

**Comment by rmrector** [comment]
The certificate error and HTTP 500 are temporary errors from their servers.

The built in fanart.tv project key is working, so likely either the add-on isn't installed correctly (if you've installed from source see the bottom of the README), or an invalid project API key is in the add-on settings.
