### ISSUE TITLE
artwork previews

### ISSUE THREAD

**Issue by mgonzales71** [rmrector/script.artwork.beef#36]
noticed the following errors in my log:

```
00:49:01.227 T:15796   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://assets.fanart.tv/preview/tv/281110/hdtvlogo/the-carbonaro-effect-590ff1b224fc6.png
00:49:01.227 T:620   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://assets.fanart.tv/preview/tv/281110/hdtvlogo/the-carbonaro-effect-5b1412de455fb.png
00:49:17.278 T:620   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://assets.fanart.tv/preview/tv/281110/hdtvlogo/the-carbonaro-effect-590ff1b224fc6.png
00:49:18.280 T:15796   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://assets.fanart.tv/preview/tv/281110/hdtvlogo/the-carbonaro-effect-5b1412de455fb.png
```

contrary to what the API docs @ https://fanarttv.docs.apiary.io/introduction/image-preview say

URL's using assets.fanart.tv are failing while simply using fanart.tv works:

https://fanart.tv/preview/tv/281110/hdtvlogo/the-carbonaro-effect-590ff1b224fc6.png
https://fanart.tv/preview/tv/281110/hdtvlogo/the-carbonaro-effect-5b1412de455fb.png

another example:

```
01:10:23.118 T:17348   ERROR: CCurlFile::Stat - Failed: Peer certificate cannot be authenticated with given CA certificates(60) for https://assets.fanart.tv/preview/tv/295647/hdclearart/blindspot-5646b46c673ae.png
01:10:23.249 T:12208   ERROR: CCurlFile::Stat - Failed: Peer certificate cannot be authenticated with given CA certificates(60) for https://assets.fanart.tv/preview/tv/295647/hdclearart/blindspot-568822f587d61.png
01:10:36.955 T:9724   ERROR: CCurlFile::Open failed with code 500 for https://assets.fanart.tv/preview/tv/295647/hdclearart/blindspot-55f3dfd07739e.png:
                                            <html>
01:10:37.351 T:17348   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://assets.fanart.tv/preview/tv/295647/hdclearart/blindspot-561d5afb1e291.png
```

all fail as well - but even more curious are the various errors from the cert failure, the 500 error and the CURLE_COULDNT_CONNECT (7) Failed to connect() to host or proxy. failure

again changing the URL to just be fanart.tv works:

https://fanart.tv/preview/tv/295647/hdclearart/blindspot-5646b46c673ae.png
https://fanart.tv/preview/tv/295647/hdclearart/blindspot-568822f587d61.png
https://fanart.tv/preview/tv/295647/hdclearart/blindspot-561d5afb1e291.png
https://fanart.tv/preview/tv/295647/hdclearart/blindspot-55f3dfd07739e.png

maybe modify the code to fallback to assets.fanart.tv *(or vice versa)?

Thanks for the awesome add on!

Mario

FYI - the cert indeed is out of date (I have noticed many online hosts that use Let's Encrypt often don't get updated for a day or two after they expire or are stop being updated at all)
 
![firefox_2018-12-07_01-17-51](https://user-images.githubusercontent.com/6510026/49639042-c8a29200-f9be-11e8-81b7-fab39a6510d5.png)

**Comment by mgonzales71** [comment]
It just dawned on me that the issue may not be with your code at all but rather a library you are using... I didn't review the code but I am betting that it's an external library.

**Comment by mgonzales71** [comment]
So insomnia strikes - got bored and looked at code.

changing line 59 of lib\providers\fanarttv.py to:

`        result['preview'] = url.replace('assets.fanart.tv/fanart/', 'fanart.tv/preview/')
`
fixes previews for fanart.tv artwork previews.

this is not what the API says to do but who knows when that was last updated right?! 
:grin:

think it's safe to assume trying to URL fanart.tv and maybe fallback to current?

I'll leave that up to you.. now maybe my brain will let me go to sleep hehe

night!

M

**Comment by mgonzales71** [comment]
FYI - changing the code in comment above fixes previews but breaks download of artwork after you select/change it.

after a few tests - noticed corrupted artwork files were downloaded (if anything was at all) - the few tests I just did saw either timeouts or partial downloads 

example: 

`Failed: Timeout was reached(28) for https://assets.fanart.tv/fanart/tv/337302/hdclearart/counterpart-5a75a1113cbe6.png`

I think I will let the expert take over now :)

**Comment by royaljack** [comment]
A friend and I started having issues similar to the above within the last few days.

**Comment by rmrector** [comment]
This is due to overloaded asset servers for fanart.tv. [Thread on their forums](https://forum.fanart.tv/viewtopic.php?f=8&t=8471)

**Comment by rmrector** [comment]
In the next version I'll have Artwork Beef display and log a message when it encounters this kind of web service error.

**Comment by craZy-C** [comment]
@rmrector Sorry to hijack a thread, just started using and I am impressed. One issue, most likely my setting, When i log into kodi and Artwork Beef does its sync and searches for art the display it leaves an overlay at the top of the screen. So While I am watching a show the text stays in the background but the overlay stays on top. When scan/download is completed it goes away. Any way of hiding this. It may be skin related. I am using Kodi 17.6 And Aeon MQ7
