### ISSUE TITLE
Artwork not downloaded if not only available at scrape time

### ISSUE THREAD

**Issue by monisriz** [rmrector/script.artwork.beef#43]
Some of the artwork (e.g. episode thumnails for newly aired episodes, new season posters for newly started seasons) does not get downloaded from online sources if such artwork is not available at the time the episode is scraped.

I use TVDB and fanart.tv for obtaining tv show artwork. For some types of artwork like episode thumbnails, it takes a few days after the episode air date for TVDB to get the episode thumb, or the season poster if it's a new season.

If the artwork is already available before the episode/season gets added/scraped then everything is good and works as usual.

Manually refreshing the episode after the artwork is available on TVDB updates the thumbnail as usual.

I believe the options/settings are correct as AB works for episodes with existing artwork. 
“Do not automatically add artwork from web services, only identify local files” - UNCHECKED.
"Check daily for old items" - CHECKED.

**Comment by rmrector** [comment]
This is by design, it works just like Kodi. Artwork Beef will not be changed to put more load on web services.

**Comment by monisriz** [comment]
I understand and appreciate the need to not put load on web services.

How about an option where users can opt to add a delay to Arwork Beef scraping newly aired episodes by “x” hours or days. The air date meta data is already scraped by the time AB kicks in and if for example the airdate was less than this “x” value then hold off scraping episode artwork until this period has passed. In my opinion 48 hours would be enough time to wait in most cases. This way no unnecessary calls to tvdb api would be made which would otherwise often return with no episode thumb image in current implementation since ep. thumb isn’t available right away.
