### ISSUE TITLE
web service error: Forbidden

### ISSUE THREAD

**Issue by mgonzales71** [rmrector/script.artwork.beef#45]
Seeing this for the last week or so
"2019-11-24 23:01:06.395 T:14652 WARNING: [script.artwork.beef] web service error: Forbidden"

Before investing time in gathering more info (debug logs, etc) wanted to see if you are already aware of this issue or not and if not what can I provide to help solve it.

Thanks

noted also online:

https://forum.kodi.tv/showthread.php?tid=258886&pid=2902534&highlight=Forbidden#pid2902534

https://www.reddit.com/r/Addons4Kodi/comments/dzfjwp/artwork_beef_web_server_forbidden/

and others

**Comment by rmrector** [comment]
It's an error from the web service, nothing I can do.
