### ISSUE TITLE
tv show thumbs not downloading

### ISSUE THREAD

**Issue by mgonzales71** [rmrector/script.artwork.beef#46]
Here is a debug log

https://paste2.org/C3pAaeV1

of me trying to use to choose artwork call to artwork beef and being told no artwork is available.

then me doing a "refresh" of the episode downloading from the internet (basically rescraping the episode) and the episode thumb is found and downloaded and processed.

can't figure out what is causing this - a bug or misconfiguration?

I have *'ed out the API keys in the log excerpt btw

Thanks

**Comment by mgonzales71** [comment]
Forgot to mention the item for this example was
 
The Late Show with Stephen Colbert
Season 5
Episode 31

**Comment by rmrector** [comment]
Artwork Beef doesn't add episode thumbs, but it can be configured to download thumbs added by scrapers. There likely wasn't an episode thumb available when the episode was first scraped.
