### ISSUE TITLE
Animated posters are not animated

### ISSUE THREAD

**Issue by hobhobuk** [rmrector/script.artwork.beef#50]
I actually had similar issues to this; https://github.com/rmrector/script.artwork.beef/issues/48
However using a Shield.  Do not have the issues when using Windows.

So that brings me onto the issue.
I could not save gifs from the shield due to the samba issue.
I have since created the entire library on Windows instead, ran Artwork beef, saved all posters, gifs etc.

So I wiped the android side, and added everything again in order to get Artwork beef to pick up the newly saved images already in the folders, and it has! However, even though its picking up the animated posters, none are animted.. they are all just static imagery, yet it shows as a Gif and as a 'animated poster'.

Seems in the process of loading the images onto the shield, its just removed all the animation from the gifs.  Leaving lower quality posters.  Other posters however are fine.

Using latest Shield 8.0.2, update released today (27th Jan)
However issue existed on previous.

**Comment by hobhobuk** [comment]
It would appear no devices show animated GIFs now. Other than the first device to scan and save the images. 

My other windows computer. And my shield. Who scanned and scrapped after. Find the GIFs but they are static images. 

Seems that only the original device which saved the images can see the animations. 

Any others just load the first frame as still. 
Checking info shows it has used a gif. But for some reason it's not animated.

**Comment by rmrector** [comment]
Animated artwork must be saved locally to the device, Kodi will not "play" them from a network drive. [Wiki page on limitations of animated artwork](https://kodi.wiki/view/Artwork_types#Limitations_of_animated_artwork).

Some part of the add-on "Skin Helper Service" can copy animated artwork locally to work around this, maybe that was / is installed on that one device.

**Comment by hobhobuk** [comment]
Thanks, I recently rebuilt my server and am now using a Windows share.
It worked from the Shield using network mount and saving without a issue now its a true windows share.

However, it just failed at saving a file and I am unsure as to why.
