### ISSUE TITLE
Pulling artwork from fanart.tv

### ISSUE THREAD

**Issue by Desperados85** [rmrector/script.artwork.beef#57]
First of all I really want to thank you for this amazing addon, it works amazing and use it all the time!

What I have noticed since the beginning is a flaw on the fanart website with the release years. When a movie shows for example (-0001) instead of (2020) the artwork won't get scraped. It never happens with tv shows only movies, I then download the artwork I need and run Artwork Beef for local artwork.

But I've been using TheMovieDB Helper addon lately and noticed it does show the artwork for these movies that have (-0001) behind the title. So I think it somehow looks for TMDB ID whether it has the right release year or not.

Is that something you could somehow implement in Artwork Beef? That would really be helpful!

Thanks :)

**Comment by rmrector** [comment]
It's an issue with fanart.tv database, post on the forum, they can fix it for individual items. https://forum.fanart.tv/viewtopic.php?f=10&t=9569

The TMDB helper addon doesn't appear to do anything more for fanart TV than AB, so if it really behaves differently then perhaps you have it configured differently. Do you have a personal key configured in one but not the other? Is it typed correctly?

**Comment by Desperados85** [comment]
A while ago I updated my library and there were quite a few movies with missing artwork, so I went to fanart.tv to check and every movie I checked was missing the release year. So I made a few requests on the forum and they added the missing years. So I then ran Artwork Beef and all artwork was scraped perfectly. 

Now and then I add another movie to my library with the same problem so I just download the artwork from the fanart.tv site manually and run Artwork Beef for local artwork as I mentioned earlier. I have copy pasted my API keys so no problem there and Artwork Beef works as expected with fanart.tv when the release year is known..

So I don't know how Artwork Beef scrapes the fanart.tv site. Does it search for TMDB ID? Or is it searching for the movie title combined with release year? I don't know if you could somehow test it for yourself?

Enola Holmes is missing release year. Fantasy Island is another one. Also The Old Guard. All Netflix movies from 2020 I believe..

**Comment by Desperados85** [comment]
I forgot to mention I'm using a Netflix skin with landscape images and clearlogos and that's the artwork I download manually when there is no release year.. Posters and fanart are always visible, because they get scraped from TMDB site I believe..

**Comment by rmrector** [comment]
Fanart.tv only supports looking up by TMDB ID or IMDB ID, there is no search. AB prefers the TMDB ID if it exists in the Kodi DB but will fall back to IMDB ID if not.

Enola Holmes works fine here. Your scraper or NFO files probably aren't adding the TMDB ID correctly. See the bottom of the [first post in the forum](https://forum.kodi.tv/showthread.php?tid=258886) for the info I need to say anything further.

**Comment by Desperados85** [comment]
OMG you're right! That's so weird, why is it only happening with movies that have (-0001) behind the title?? The original NFO file said https://www.themoviedb.org/movie/497582, which is what every library item from the TheMovieDB addon looks like.. 

So I opened the metadata editor addon and saw TMDB ID n/a, which is weird, so I typed 497582 and updated the NFO file, then ran Artwork Beef again and the landscape image and clearlogo were added!

So thanks for helping me out here :)

Do you have any idea why I only have this issue with movies that are missing release year?!

**Comment by Desperados85** [comment]
So I just did a test and added Fantasy Island to my library. On the fanart site it says (-0001) behind the title and as expected I didn't get the landscape image and clearlogo. I then opened the Metadata Editor and looked for TMDB ID, it said n/a, so I typed in the right ID, didn't even update the NFO file and ran Artwork Beef straight away, and it worked!

So then I added Wonder Woman 84 to my library, which is still in production but already says (2020) on the fanart site. Artwork Beef did its magic and downloaded all the artwork including the landscape image and the clearlogo. So I opened the Metadata Editor to check for TMDB ID and it also said n/a but still gave me all the artwork from fanart.tv!

I randomly selected a few movies in my library and they're all missing the TMDB ID. But maybe they get scraped with the IMDb ID which are mentioned..

I scrape my library using the Universal Movie Scraper and have looked in the settings, but can't seem to find the solution for scraping TMDB ID correctly.. In the last section 'search' and 'search engine to use' mine says IMDb but can be switched to TMDB, maybe that could be it?

**Comment by Desperados85** [comment]
So yeah that was indeed the solution.. Added Project Power to my library which I couldn't even find on the fanart.tv site! But it scraped all my artwork perfect, and when checking the Metadata both IMDb and TMDb ID are there now :) There should be a better tutorial on using the Universal Movie Scraper.. Jeez..
