### ISSUE TITLE
Artwork beef not DLing or displaying art from "Fanart.tv"...since 28.5

### ISSUE THREAD

**Issue by HockeyGuy7** [rmrector/script.artwork.beef#58]
Hi

Was auto updated to "AB 28.5" today. Everything was working perfectly yesterday, but since the update AB is downloading remote art all wrong!

- It DLs some but not all fanart, and posters. "Remote art" does not display...shows blank(Was working yesterday)
- It DLs NOTHING from fanart.tv (was yesterday)
- Does not DL and load to display logos from fanart.tv (manual or auto)

API keys have been added...does not fix issue.
Issue happens with both movies and TV shows

PLEASE fix this issue ASAP!!! Major annoying....like said everything was working great yesterday, and did not change anything(settings)
Also...please include "older versions" of Artwork beef to rollback if needed for issues like this one....I wish I could just go back to the older version I had yesterday, but I dont know where I can find older versions of AB.

Thanks

**Comment by rmrector** [comment]
It was a fanart.tv web service thing, not AB, it's just a coincidence their service had an issue at the same time as you got the new version. As noted in the UI popup message and Kodi's log.
