### ISSUE TITLE
[Artwork Dump] Not all artwork is downloaded

### ISSUE THREAD

**Issue by KarellenX** [rmrector/script.artwork.beef#59]
Having used this for a couple of tv shows already, I noticed that not all artwork is downloaded after the scraping process. But if I then run the add-on again from the add-on list, the remaining artwork is downloaded.

Fargo S4 - https://www.themoviedb.org/tv/60622-fargo/season/4/images/posters
fanart.tv - https://fanart.tv/series/269613/fargo/

In this instance, Season artwork was not downloaded. 
Log... https://paste.kodi.tv/adiyewifow.kodi

Line 3580 is start of artwork.dump process
Line 3737 is end of artwork.dump process
Line 3946 downloading Season poster, but this was not downloaded by artwork.dump

If I then run the add-on again, the season poster is downloaded also.

I noticed this with movies also, especially the movie set artwork, which required re-running the add-on.

Maybe artwork,dump is running too quickly after the scrape?

You stated in the artwork beef thread that this add-on changes the artwork paths. I ran an Export to nfo files and I see  no changes in artwork paths. They all still point to TheMovieDB and fanart.tv... https://paste.kodi.tv/uyemecuxej or are you referring to something else?

Also, would it be better to start a new thread on the forum for this add-on? It has a different name and supported only in v19.

**Comment by rmrector** [comment]
Thanks, I think I found it. Updating an individual item goes through a different process that missed the seasons of a new TV show.

> I ran an Export to nfo files and I see no changes in artwork paths.

It changes the paths to _assigned_ artwork (the artwork skins can actually display), it cannot change the other available-but-not-assigned artwork. No JSON-RPC interface is available to modify those.

> Also, would it be better to start a new thread on the forum for this add-on? It has a different name and supported only in v19.

Eventually.

**Comment by KarellenX** [comment]
Thanks @rmrector 

One more question...

>It changes the paths to assigned artwork (the artwork skins can actually display), it cannot change the other available-but-not-assigned artwork. No JSON-RPC interface is available to modify those.

Is this the reason why now when I run an Export to Separate Files and include exporting artwork, no artwork is exported?

Artwork dump saves the files with the short artwork names.
Kodi Export saves exported artwork with long artwork names. These are no longer exported for those movies that Artwork Dump has downloaded artwork for.

_(in case you are wondering, I still export for the actors images, then delete the other exported artwork as I have local artwork)_

**Comment by rmrector** [comment]
> Is this the reason why now when I run an Export to Separate Files and include exporting artwork, no artwork is exported?

As far as I know Kodi exports everything in its texture cache. Are the images cached? That log for Fargo noted that AD wasn't able to cache the images due to Kodi settings, so unless you did something else to cache the new image Kodi doesn't have anything to export.

> [script.artwork.dump] Artwork caching requires Kodi setting 'Allow remote control via HTTP' enabled

**Comment by KarellenX** [comment]
>That log for Fargo noted that AD wasn't able to cache the images due to Kodi settings

Doesn't Kodi automatically cache the images after scraping? It always has in the past and it has never been an issue until AD was installed.
I have never needed to enable "Allow remote control via HTTP" in the past.
How is Kodi being prevented from caching as it would normally?

**Comment by rmrector** [comment]
AD changes things. That is the point of the tool.

Kodi identifies cached artwork by its path - when the path changes Kodi needs to cache the new path. Kodi doesn't automatically download every image to cache when they are changed after the scrape, AD has to do it.

**Comment by KarellenX** [comment]
Got it. Thanks.

**Comment by rmrector** [comment]
0.1.2 should fix this.

And I've pushed it to a new GH repo https://github.com/rmrector/script.artwork.dump
